// S.P.O.T Security Patrol Operations Tracker - Enterprise Mock Telemetry Dataset

export const MOCK_GUARDS = [
  {
    id: 'G-101',
    name: 'Johnathan Vance',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    client: 'Cyberdyne Systems Corp',
    siteId: 'SITE-01',
    siteName: 'Central Logistics Warehouse',
    siteType: 'Warehouse',
    shift: 'Day Shift (06:00 - 18:00)',
    status: 'On Patrol', // On Patrol, Idle, Off Duty, Emergency
    battery: 92,
    gpsAccuracy: '1.2m (Excellent)',
    gpsLat: 14.5547,
    gpsLng: 121.0244,
    faceVerified: true,
    faceVerifiedAt: '08:45 AM',
    currentPatrolId: 'PAT-8801',
    currentPatrolName: 'Perimeter Outer Fence & Gate 4',
    progressPct: 75,
    completedCheckpoints: 6,
    totalCheckpoints: 8,
    etaMinutes: 12,
    phone: '+63 917 555 0192',
    joinDate: '2023-04-12',
    performanceRating: 98.4,
    incidentsReportedCount: 3,
    attendanceRate: 99.2
  },
  {
    id: 'G-102',
    name: 'Marcus Sterling',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    client: 'Apex Financial Tower',
    siteId: 'SITE-02',
    siteName: 'Apex Corporate HQ Plaza',
    siteType: 'Office',
    shift: 'Day Shift (06:00 - 18:00)',
    status: 'On Patrol',
    battery: 78,
    gpsAccuracy: '2.5m (Good)',
    gpsLat: 14.5589,
    gpsLng: 121.0288,
    faceVerified: true,
    faceVerifiedAt: '09:10 AM',
    currentPatrolId: 'PAT-8802',
    currentPatrolName: 'Executive Floors & Server Vault',
    progressPct: 40,
    completedCheckpoints: 4,
    totalCheckpoints: 10,
    etaMinutes: 24,
    phone: '+63 918 444 0281',
    joinDate: '2022-09-01',
    performanceRating: 96.8,
    incidentsReportedCount: 1,
    attendanceRate: 98.5
  },
  {
    id: 'G-103',
    name: 'Elena Rostova',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    client: 'St. Jude Healthcare Group',
    siteId: 'SITE-03',
    siteName: 'Metro General Hospital East',
    siteType: 'Hospital',
    shift: 'Day Shift (06:00 - 18:00)',
    status: 'Emergency',
    battery: 18,
    gpsAccuracy: '4.8m (Warning)',
    gpsLat: 14.5492,
    gpsLng: 121.0199,
    faceVerified: true,
    faceVerifiedAt: '07:30 AM',
    currentPatrolId: 'PAT-8803',
    currentPatrolName: 'ER Zone & ICU Back Corridor',
    progressPct: 20,
    completedCheckpoints: 1,
    totalCheckpoints: 5,
    etaMinutes: 45,
    phone: '+63 920 333 9911',
    joinDate: '2024-01-15',
    performanceRating: 91.2,
    incidentsReportedCount: 7,
    attendanceRate: 95.0
  },
  {
    id: 'G-104',
    name: 'Robert Cruz',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    client: 'Greenfield Estate Development',
    siteId: 'SITE-04',
    siteName: 'Highland Luxury Subdivision',
    siteType: 'Subdivision',
    shift: 'Day Shift (06:00 - 18:00)',
    status: 'Idle',
    battery: 88,
    gpsAccuracy: '1.0m (Excellent)',
    gpsLat: 14.5621,
    gpsLng: 121.0312,
    faceVerified: true,
    faceVerifiedAt: '09:00 AM',
    currentPatrolId: 'PAT-8804',
    currentPatrolName: 'North Gate Entrance & Clubhouse',
    progressPct: 100,
    completedCheckpoints: 6,
    totalCheckpoints: 6,
    etaMinutes: 0,
    phone: '+63 928 111 8822',
    joinDate: '2021-11-20',
    performanceRating: 99.1,
    incidentsReportedCount: 2,
    attendanceRate: 100.0
  },
  {
    id: 'G-105',
    name: 'David Kim',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80',
    client: 'Grand Plaza Malls Inc.',
    siteId: 'SITE-05',
    siteName: 'Grand City Megamall Complex',
    siteType: 'Mall',
    shift: 'Night Shift (18:00 - 06:00)',
    status: 'On Patrol',
    battery: 64,
    gpsAccuracy: '1.8m (Good)',
    gpsLat: 14.5511,
    gpsLng: 121.0267,
    faceVerified: true,
    faceVerifiedAt: '09:15 AM',
    currentPatrolId: 'PAT-8805',
    currentPatrolName: 'Basement Parking & Fire Exit Sweep',
    progressPct: 60,
    completedCheckpoints: 3,
    totalCheckpoints: 5,
    etaMinutes: 18,
    phone: '+63 919 777 4433',
    joinDate: '2023-08-10',
    performanceRating: 95.5,
    incidentsReportedCount: 4,
    attendanceRate: 97.8
  },
  {
    id: 'G-106',
    name: 'Sarah Connor',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    client: 'Horizon International Academy',
    siteId: 'SITE-06',
    siteName: 'Horizon Academy Campus',
    siteType: 'School',
    shift: 'Day Shift (06:00 - 18:00)',
    status: 'Off Duty',
    battery: 95,
    gpsAccuracy: 'Offline',
    gpsLat: 14.5450,
    gpsLng: 121.0210,
    faceVerified: false,
    faceVerifiedAt: 'Yesterday',
    currentPatrolId: 'PAT-8806',
    currentPatrolName: 'Science Wing & Athletic Field',
    progressPct: 0,
    completedCheckpoints: 0,
    totalCheckpoints: 7,
    etaMinutes: 0,
    phone: '+63 917 222 9900',
    joinDate: '2022-03-05',
    performanceRating: 97.0,
    incidentsReportedCount: 0,
    attendanceRate: 99.0
  }
];

export const MOCK_SITES = [
  {
    id: 'SITE-01',
    name: 'Central Logistics Warehouse',
    type: 'Warehouse',
    client: 'Cyberdyne Systems Corp',
    address: 'Zone 4 Industrial Park, South Superhighway',
    activeGuardsCount: 3,
    checkpointsCount: 12,
    routesCount: 4,
    incidentsCount: 1,
    status: 'Active',
    lat: 14.5547,
    lng: 121.0244,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=500&q=80'
  },
  {
    id: 'SITE-02',
    name: 'Apex Corporate HQ Plaza',
    type: 'Office',
    client: 'Apex Financial Tower',
    address: 'Financial District Financial Center 5th Ave',
    activeGuardsCount: 5,
    checkpointsCount: 18,
    routesCount: 6,
    incidentsCount: 0,
    status: 'Active',
    lat: 14.5589,
    lng: 121.0288,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=500&q=80'
  },
  {
    id: 'SITE-03',
    name: 'Metro General Hospital East',
    type: 'Hospital',
    client: 'St. Jude Healthcare Group',
    address: '88 Healthcare Blvd, East Medical Sector',
    activeGuardsCount: 4,
    checkpointsCount: 15,
    routesCount: 5,
    incidentsCount: 2,
    status: 'Critical Alert',
    lat: 14.5492,
    lng: 121.0199,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=500&q=80'
  },
  {
    id: 'SITE-04',
    name: 'Highland Luxury Subdivision',
    type: 'Subdivision',
    client: 'Greenfield Estate Development',
    address: 'Highland Estates Gate 1, Ridge View',
    activeGuardsCount: 4,
    checkpointsCount: 14,
    routesCount: 4,
    incidentsCount: 0,
    status: 'Active',
    lat: 14.5621,
    lng: 121.0312,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=500&q=80'
  },
  {
    id: 'SITE-05',
    name: 'Grand City Megamall Complex',
    type: 'Mall',
    client: 'Grand Plaza Malls Inc.',
    address: 'Commercial Avenue Corner 12th Expressway',
    activeGuardsCount: 8,
    checkpointsCount: 24,
    routesCount: 8,
    incidentsCount: 1,
    status: 'Active',
    lat: 14.5511,
    lng: 121.0267,
    image: 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=500&q=80'
  },
  {
    id: 'SITE-06',
    name: 'Horizon Academy Campus',
    type: 'School',
    client: 'Horizon International Academy',
    address: '100 University Belt Expressway',
    activeGuardsCount: 2,
    checkpointsCount: 10,
    routesCount: 3,
    incidentsCount: 0,
    status: 'Normal',
    lat: 14.5450,
    lng: 121.0210,
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=500&q=80'
  }
];

export const MOCK_CLIENTS = [
  {
    id: 'CLI-01',
    company: 'Cyberdyne Systems Corp',
    contactPerson: 'Director Sarah Connor',
    email: 's.connor@cyberdyne.io',
    phone: '+63 2 8888 1000',
    deploymentsCount: 3,
    assignedGuards: 12,
    supervisor: 'Captain Marcus Vance',
    status: 'Active Contract',
    slaCompliance: 99.5
  },
  {
    id: 'CLI-02',
    company: 'Apex Financial Tower',
    contactPerson: 'Mr. Arthur Pendelton',
    email: 'pendelton@apexfin.com',
    phone: '+63 2 8777 2200',
    deploymentsCount: 2,
    assignedGuards: 16,
    supervisor: 'Inspector Helen Ramos',
    status: 'Active Contract',
    slaCompliance: 98.8
  },
  {
    id: 'CLI-03',
    company: 'St. Jude Healthcare Group',
    contactPerson: 'Dr. Elizabeth Shaw',
    email: 'eshaw@stjude-health.org',
    phone: '+63 2 8555 3300',
    deploymentsCount: 4,
    assignedGuards: 20,
    supervisor: 'Supervisor Robert Blake',
    status: 'Active Contract',
    slaCompliance: 96.2
  },
  {
    id: 'CLI-04',
    company: 'Greenfield Estate Development',
    contactPerson: 'Engr. Michael Thorne',
    email: 'm.thorne@greenfield.ph',
    phone: '+63 2 8444 9911',
    deploymentsCount: 2,
    assignedGuards: 8,
    supervisor: 'Captain Marcus Vance',
    status: 'Active Contract',
    slaCompliance: 100.0
  }
];

export const MOCK_PATROLS = [
  {
    id: 'PAT-8801',
    guardId: 'G-101',
    guardName: 'Johnathan Vance',
    guardPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    siteName: 'Central Logistics Warehouse',
    routeName: 'Perimeter Outer Fence & Gate 4 Sweep',
    status: 'In Progress',
    progressPct: 75,
    completedCount: 6,
    totalCount: 8,
    remainingCount: 2,
    etaMinutes: 12,
    startTime: '09:00 AM',
    checkpoints: [
      { id: 'CP-01', name: 'Gate 1 Guard House', status: 'Completed', scannedAt: '09:04 AM', method: 'QR Scan + Face' },
      { id: 'CP-02', name: 'North Loading Dock A', status: 'Completed', scannedAt: '09:12 AM', method: 'QR Scan' },
      { id: 'CP-03', name: 'Fuel Storage Perimeter', status: 'Completed', scannedAt: '09:19 AM', method: 'NFC Tap + GPS' },
      { id: 'CP-04', name: 'East Boundary Fence #3', status: 'Completed', scannedAt: '09:25 AM', method: 'QR Scan' },
      { id: 'CP-05', name: 'Gate 4 Secondary Entry', status: 'Completed', scannedAt: '09:31 AM', method: 'QR Scan + Face' },
      { id: 'CP-06', name: 'Warehouse Bay 12', status: 'Completed', scannedAt: '09:38 AM', method: 'QR Scan' },
      { id: 'CP-07', name: 'HVAC Transformer Room', status: 'Pending', scannedAt: null, method: 'Pending Scan' },
      { id: 'CP-08', name: 'South Gate Return Point', status: 'Pending', scannedAt: null, method: 'Pending Scan' }
    ]
  },
  {
    id: 'PAT-8802',
    guardId: 'G-102',
    guardName: 'Marcus Sterling',
    guardPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    siteName: 'Apex Corporate HQ Plaza',
    routeName: 'Executive Floors & Server Vault Patrol',
    status: 'In Progress',
    progressPct: 40,
    completedCount: 4,
    totalCount: 10,
    remainingCount: 6,
    etaMinutes: 24,
    startTime: '09:15 AM',
    checkpoints: [
      { id: 'CP-21', name: 'Lobby Security Gate', status: 'Completed', scannedAt: '09:17 AM', method: 'QR Scan + Face' },
      { id: 'CP-22', name: '3rd Floor Server Vault', status: 'Completed', scannedAt: '09:24 AM', method: 'Biometric + QR' },
      { id: 'CP-23', name: '5th Floor Executive Hall', status: 'Completed', scannedAt: '09:30 AM', method: 'QR Scan' },
      { id: 'CP-24', name: '8th Floor Boardroom', status: 'Completed', scannedAt: '09:36 AM', method: 'QR Scan' },
      { id: 'CP-25', name: '12th Floor Terrace Exit', status: 'Pending', scannedAt: null, method: 'Pending' }
    ]
  },
  {
    id: 'PAT-8803',
    guardId: 'G-103',
    guardName: 'Elena Rostova',
    guardPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    siteName: 'Metro General Hospital East',
    routeName: 'ER Zone & ICU Back Corridor',
    status: 'Delayed / SOS',
    progressPct: 20,
    completedCount: 1,
    totalCount: 5,
    remainingCount: 4,
    etaMinutes: 45,
    startTime: '08:45 AM',
    checkpoints: [
      { id: 'CP-31', name: 'ER Triage Gate', status: 'Completed', scannedAt: '08:50 AM', method: 'QR Scan' },
      { id: 'CP-32', name: 'ICU Rear Service Elevator', status: 'Missed', scannedAt: null, method: 'Missed Target' }
    ]
  }
];

export const MOCK_INCIDENTS = [
  {
    id: 'INC-9901',
    title: 'Unauthorized Rear Door Breach Alert',
    priority: 'High', // High, Medium, Low
    siteName: 'Metro General Hospital East',
    location: 'ICU Back Corridor Service Gate',
    reporterName: 'Elena Rostova',
    reporterId: 'G-103',
    timestamp: '09:21 AM Today',
    status: 'Investigating', // Investigating, Resolved, Escalated
    evidencePhoto: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80',
    description: 'Security sensor triggered at service elevator. Unidentified individual attempted to bypass badge scanner. Guard dispatched.',
    actionsTaken: 'Dispatched secondary supervisor. Local security log recorded.'
  },
  {
    id: 'INC-9902',
    title: 'Broken Perimeter Lighting Fixture',
    priority: 'Medium',
    siteName: 'Central Logistics Warehouse',
    location: 'East Boundary Fence #3',
    reporterName: 'Johnathan Vance',
    reporterId: 'G-101',
    timestamp: '08:14 AM Today',
    status: 'Resolved',
    evidencePhoto: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
    description: 'Floodlight #4 shattered due to strong wind gust. Area temporary illuminated with backup spotlight.',
    actionsTaken: 'Maintenance request #4092 logged. Work order assigned.'
  },
  {
    id: 'INC-9903',
    title: 'Visitor Badge Scan Mismatch',
    priority: 'Low',
    siteName: 'Apex Corporate HQ Plaza',
    location: 'Lobby Turnstile 2',
    reporterName: 'Marcus Sterling',
    reporterId: 'G-102',
    timestamp: '07:45 AM Today',
    status: 'Resolved',
    evidencePhoto: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=600&q=80',
    description: 'Contractor presented expired guest pass. Verified credentials with front reception.',
    actionsTaken: 'Issued temporary day badge.'
  }
];

export const MOCK_AUDIT_LOGS = [
  {
    id: 'LOG-7001',
    timestamp: '09:31:12 AM',
    actor: 'Johnathan Vance (Guard)',
    category: 'Verification', // Login, Logout, Created, Updated, Deleted, Verification, Synchronization, System Change
    action: 'Completed Checkpoint 5 (Gate 4 Secondary Entry)',
    details: 'QR Code matched. GPS accuracy 1.2m. Face verification score 99.4%.',
    ipAddress: '192.168.10.45',
    severity: 'Info'
  },
  {
    id: 'LOG-7002',
    timestamp: '09:27:04 AM',
    actor: 'Marcus Sterling (Guard)',
    category: 'Verification',
    action: 'Face Verification Passed',
    details: 'Liveness check verified on Samsung Knox Active Tab.',
    ipAddress: '192.168.10.72',
    severity: 'Info'
  },
  {
    id: 'LOG-7003',
    timestamp: '09:21:40 AM',
    actor: 'Elena Rostova (Guard)',
    category: 'System Change',
    action: 'Emergency Incident Alert Submitted',
    details: 'Priority HIGH triggered at Metro General Hospital East.',
    ipAddress: '192.168.12.19',
    severity: 'Critical'
  },
  {
    id: 'LOG-7004',
    timestamp: '09:15:00 AM',
    actor: 'Supervisor Admin',
    category: 'Login',
    action: 'Supervisor Web Command Console Login',
    details: 'Authenticated via Firebase Auth 2FA.',
    ipAddress: '112.198.70.12',
    severity: 'Info'
  },
  {
    id: 'LOG-7005',
    timestamp: '08:59:18 AM',
    actor: 'System Daemon',
    category: 'Synchronization',
    action: 'Firebase Cloud DB Sync Sync Completed',
    details: 'Synced 142 checkpoint events and 18 guard GPS tracks.',
    ipAddress: 'Internal DB Cluster',
    severity: 'Info'
  }
];

export const MOCK_LIVE_EVENTS = [
  { id: 'EV-01', time: '09:31 AM', text: 'John Vance completed Checkpoint 5 at Central Logistics Warehouse', type: 'checkpoint', icon: 'CheckCircle2' },
  { id: 'EV-02', time: '09:27 AM', text: 'Marcus Sterling Face Verification Passed (99.4% match score)', type: 'verify', icon: 'ShieldCheck' },
  { id: 'EV-03', time: '09:25 AM', text: 'QR Scan Success: East Boundary Fence #3', type: 'scan', icon: 'QrCode' },
  { id: 'EV-04', time: '09:21 AM', text: 'Emergency SOS Alert Submitted by Elena Rostova', type: 'alert', icon: 'AlertTriangle' },
  { id: 'EV-05', time: '09:20 AM', text: 'Guard Started Patrol PAT-8802 (Executive Floors)', type: 'start', icon: 'Play' },
  { id: 'EV-06', time: '09:12 AM', text: 'Robert Cruz completed Patrol PAT-8804 (100% Rate)', type: 'checkpoint', icon: 'CheckCircle2' }
];

export const MOCK_ANALYTICS_STATS = {
  activeGuards: 24,
  currentlyOnPatrol: 18,
  todaysPatrols: 142,
  completedPatrols: 128,
  delayedPatrols: 10,
  missedPatrols: 4,
  offlineGuards: 2,
  incidentsToday: 3,
  
  // High impact metrics for supervisor
  avgPatrolDurationMinutes: 38.4,
  avgDelayMinutes: 4.2,
  attendanceRate: 98.6,
  faceVerificationSuccessRate: 99.2,
  offlineSessionsCount: 3,
  synchronizationSuccessRate: 100.0,
  qrCompletionRate: 97.8,
  gpsAccuracyMeters: 1.6
};
